//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        public long id { get; set; }
        public string Name { get; set; }
        public string OrgType_Type { get; set; }
        public string Address { get; set; }
        public long INN { get; set; }
        public long KPP { get; set; }
        public string DirName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
        public int Priority { get; set; }
    
        public virtual orgtype orgtype { get; set; }
    }
}
