//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliveryhistory
    {
        public long Provider_id { get; set; }
        public long Materials_id { get; set; }
        public System.DateTime Date { get; set; }
        public double Amount { get; set; }
    
        public virtual material material { get; set; }
        public virtual provider provider { get; set; }
    }
}
