//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public long id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime Birthday { get; set; }
        public int PassNumber { get; set; }
        public int BankNumber { get; set; }
        public int FamilySize { get; set; }
        public string Specialization { get; set; }
        public string NFC { get; set; }
    }
}
