//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShelestDBEntities : DbContext
    {
        public ShelestDBEntities()
            : base("name=ShelestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agent> agents { get; set; }
        public virtual DbSet<deliveryhistory> deliveryhistories { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<lognfc> lognfcs { get; set; }
        public virtual DbSet<material> materials { get; set; }
        public virtual DbSet<materialtype> materialtypes { get; set; }
        public virtual DbSet<orgtype> orgtypes { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productsale> productsales { get; set; }
        public virtual DbSet<productscanbeproduced> productscanbeproduceds { get; set; }
        public virtual DbSet<productsneedmaterial> productsneedmaterials { get; set; }
        public virtual DbSet<producttype> producttypes { get; set; }
        public virtual DbSet<provider> providers { get; set; }
        public virtual DbSet<workshop> workshops { get; set; }
    }
}
