//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public long id { get; set; }
        public string VendorCode { get; set; }
        public string Name { get; set; }
        public string ProductType_Type { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public decimal MinimalCost { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> WeightWrapped { get; set; }
        public string Certificate { get; set; }
        public string Standard { get; set; }
        public Nullable<System.TimeSpan> ProductionDuration { get; set; }
        public Nullable<decimal> BaseCost { get; set; }
    
        public virtual producttype producttype { get; set; }
    }
}
